---
config:
  layout: dagre
---
flowchart TD
    A["Inicio"] --> B{"Pestaña Inicial: Login"}
    B -- Registrarse --> C["Pestaña de Registro de Usuario"]
    B -- Ya tiene cuenta --> D["Pestaña del Dashboard Principal"]
    C --> D
    D -- Registro de Animales --> E["Pestaña de Registro de Animales"]
    D -- Solicitar Análisis --> F["Pestaña de Solicitud de Análisis"]
    D -- Gestión de Análisis --> G["Pestaña de Gestionar Análisis"]
    E --> D
    F -- Seleccionar Animal y Tipo de Análisis, Fecha --> H["Cita Agendada para Toma de Muestra"]
    F --> D
    G -- Seleccionar Animal y Examen --> I["Visualización de Resultados en Tabla"]
    G --> D
    H --> G
